POST https://myshop-hmthien-default-rtdb.asia-southeast1.firebasedatabase.app/products.json
//firebasedatabase.app/products.json?auth=
Content-Type: application/json

{
"creatorId": "cy9uecJW3ugBqw0MnwBuE97U44F3",
"description": "Prepare any meal you want.",
"imageUrl": "https://upload.wikimedia.org/.../1024px-Cast-Iron-Pan.jpg",
"price": 49.99,
"title": "A Pan"
}

###

GET  https://myshop-hmthien-default-rtdb.asia-southeast1.firebasedatabase.app/products/-NW8E4UR0c4bnBEbqQrF.json